// WebVTT.js

window.webvtt = ({
	
	'version': '0.0.1',
	
	'WebVTT': function() {

		// Array of WebVTTCaptions
		this.captions = new Array();

		// Outputs WebVTT file
		this.toFile = function() {
			var out = "WEBVTT\n\n";

			out += "NOTE Generated by webvtt.js\n\n";

			for(captionIndex in this.captions) {
				var caption = this.captions[captionIndex];
				out += caption.formatTime(caption.startTime) + " --> " + caption.formatTime(caption.endTime) + "\n";
				out += caption.captionText + "\n";
			}

			return out;
		}

	},
	
	'WebVTTCaption': function() {

		this.startTime   = 0.000;
		this.endTime     = 0.000;
		this.captionText = "";

		// Converts a double to WebVTT's 00:00.000 time formart
		this.formatTime = function(time) {
			return ""; 
		}

	}
	
});
